from typing import Protocol, Any

class IGameCollectionDbContext(Protocol):
    def add(self, obj: Any) -> None: ...
    def commit(self) -> None: ...
    def refresh(self, obj: Any) -> None: ...
    def execute(self, statement: Any): ...
    def delete(self, obj: Any) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...